### ISSUE TITLE
Missing include file

### ISSUE THREAD

**Issue by Mainuss** [leifo/haujobb-amiga#1]
Two missing file errors on:
- wickedlink.s (in 77):
   include	wos.i
- wickedquicklink.s (in 114)
   include	wos.i

I've could fixed them changing both lines with:
   **include	wos:includes/wos.i**

It's ok?

PS1: To compile with devpac I've had to assign devpac: volume due to lines 15 and 16 in go file,
PS2: I can't see executable files after compilation

**Comment by leifo** [comment]
Thanks for the first issue! :)

Did Devpac produce wickedlink.o and wickedquicklink.o? That should be the result.

If so, you should be able to build the stars example project.

(Will remove Devpac dependancy before long.)

**Comment by Mainuss** [comment]
My pleasure ;)

Yes, both .o files were built.

How can I build starts?

**Comment by leifo** [comment]
Solved the issue in a platform neutral way (no Amiga assigns).
Also temporarily added the .o files until build-process no longer relies in Devpac.

Building /examples/stars is another issue. (It requires VBCC Posixlib which I didn't document, yet. Get it from [Aminet](http://aminet.net/package/dev/c/vbcc_PosixLib.lha).)

**Comment by Mainuss** [comment]
Ok.
I've downloaded last fixes, adding posix.lib to build directory and "make all".
+ It works on Windows side.
- It crash on Amiga side.

I'm ready for more testing when you like.
