### ISSUE TITLE
Fix -Iposix compile option

### ISSUE THREAD

**Issue by Mainuss** [leifo/haujobb-amiga#3]
Fix missing Posix library to "make" examples on PC side:
- Fatal error 8: Cannot open "-lposix": No such file or directory.

* it doesn't work declaring library path C:\vbcc\posix\AmigaOS3 on Windows, but it works copying the posix.lib in the /build dir

**Comment by leifo** [comment]
Turned out we didn't need posix.lib for the three examples, so I removed the dependency with the latest commit. Could you please confirm that it works?

**Comment by Mainuss** [comment]
It's fixed ! good job.


ps: plz, read last message on fb
